language: shell
jobs:
  include:
    - name: AppImage
      dist: bionic
    - name: "Windows"
      os: windows
      before_install:
        - choco install python --version 3.9.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python39:/c/Python39/Scripts:$PATH

env:
  - VERSION=continuous
install: >
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sh ./build-appimage.sh
  else
    pip3 install --upgrade pip
    pip3 install pyinstaller .
    cd bin
    pyinstaller -F minimal-podcasts-player -i mpp.ico --add-data "../mpp/ddbb.sql;mpp" --add-data "../mpp/locales;mpp/locales" -n minimal-podcasts-player-continuous
  fi

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Alfonso Saavedra 'Son Link'"
  - git config --local user.email "sonlink.dourden@gmail.com"
  #- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - export TRAVIS_TAG=continuous
  # - git tag $TRAVIS_TAG
  - echo $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file:
    - Minimal_Podcasts_Player-$VERSION-x86_64.AppImage
    - $TRAVIS_BUILD_DIR/bin/dist/minimal-podcasts-player-continuous.exe
  skip_cleanup: true
  overwrite: true
  draft: true
