language: shell
jobs:
  include:
    - name: AppImage
      dist: bionic

env:
  - VERSION=''

before_install:
  # Set up git user name and tag this commit
  - git config --local user.name "Alfonso Saavedra 'Son Link'"
  - git config --local user.email "sonlink.dourden@gmail.com"
  - VERSION=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')}
  - export TRAVIS_TAG=${$VERSION)-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh ./build-appimage.sh; fi

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: Minimal_Podcasts_Player-$VERSION-x86_64.AppImage
  cleanup: true
  overwrite: true
  on:
    tags: false
