language: shell
jobs:
  include:
    - name: AppImage
      dist: bionic
    - name: "Windows"
      os: windows
      before_install:
        - choco install python --version 3.9.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python39:/c/Python39/Scripts:$PATH

env:
  - VERSION=''

before_install:
  # Set up git user name and tag this commit
  - VERSION=$(date +'%Y%m%d%H%M%S')
install: >
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sh ./build-appimage.sh
  else
    pip3 install --upgrade pip
    pip3 install pyinstaller .
    cd bin
    pyinstaller -F minimal-podcasts-player -i mpp.ico --add-data "../mpp/ddbb.sql;mpp" --add-data "../mpp/locales;mpp/locales"
  fi

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Minimal_Podcasts_Player-$VERSION-x86_64.AppImage bin/dist/minimal-podcasts-player.exe

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/