language: shell
jobs:
  include:
    - name: AppImage
      dist: bionic
    - name: "Windows"
      os: windows
      before_install:
        - choco install python --version 3.9.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python39:/c/Python39/Scripts:$PATH

env:
  - VERSION=$(date +'%Y%m%d%H%M%S')
install: >
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sh ./build-appimage.sh
  else
    pip3 install --upgrade pip
    pip3 install pyinstaller .
    cd bin
    pyinstaller -F minimal-podcasts-player -i mpp.ico --add-data "../mpp/ddbb.sql;mpp" --add-data "../mpp/locales;mpp/locales"
  fi

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Alfonso Saavedra 'Son Link'"
  - git config --local user.email "sonlink.dourden@gmail.com"
  #- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - export TRAVIS_TAG=continuous
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file:
    - Minimal_Podcasts_Player-$VERSION-x86_64.AppImage
    - bin\dist\minimal-podcasts-player.exe
  skip_cleanup: true
#after_success:
#  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
#  - chmod +x upload.sh
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./upload.sh Minimal_Podcasts_Player-$VERSION-x86_64.AppImage; fi
#  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./upload.sh bin/dist/minimal-podcasts-player.exe; fi

#branches:
#  except:
#    - # Do not build tags that we create when we upload to GitHub Releases
#    - /^(?i:continuous)$/