language: shell
jobs:
  include:
    - name: AppImage
      dist: bionic

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh ./build-appimage.sh; fi

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "YOUR GIT USER NAME"
  - git config --local user.email "YOUR GIT USER EMAIL"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: Minimal_Podcasts_Player-$TRAVIS_TAG-x86_64.AppImage
  cleanup: true
  on:
    tags: true
