language: shell
jobs:
  include:
    - name: AppImage
      dist: bionic

env:
  - VERSION=''

before_install:
  # Set up git user name and tag this commit
  - VERSION=$(date +'%Y%m%d%H%M%S')
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh ./build-appimage.sh; fi

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Minimal_Podcasts_Player-$VERSION-x86_64.AppImage

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/