language: shell
jobs:
  include:
    - name: AppImage
      dist: bionic
    - name: "Windows"
      os: windows
      before_install:
        - choco install python --version 3.9.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python39:/c/Python39/Scripts:$PATH
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell

env:
  - VERSION=continuous
install: >
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sh ./build-appimage.sh
  elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    pip3 install --upgrade pip
    pip3 install pyinstaller .
    cd bin
    pyinstaller -F minimal-podcasts-player -i mpp.ico --add-data "../mpp/ddbb.sql;mpp" --add-data "../mpp/locales;mpp/locales" -n minimal-podcasts-player-continuous
  else
    pip3 install --upgrade pip
    pip3 install pyinstaller .
    cd bin
    pyinstaller --windowed minimal-podcasts-player -i mpp.icns --add-data "../mpp/ddbb.sql:mpp" --add-data "../mpp/locales:mpp/locales" -n minimal-podcasts-player-continuous
    pushd dist
    hdiutil create ./minimal-podcasts-player-continuous.dmg -srcfolder minimal-podcasts-player-continuous.app -ov
    popd

  fi

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Alfonso Saavedra 'Son Link'"
  - git config --local user.email "sonlink.dourden@gmail.com"
  #- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - export TRAVIS_TAG=$VERSION
deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file:
      - Minimal_Podcasts_Player-continuous-x86_64.AppImage
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file:
      - $TRAVIS_BUILD_DIR/bin/dist/minimal-podcasts-player-continuous.exe
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = windows
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file:
      - $TRAVIS_BUILD_DIR/bin/dist/minimal-podcasts-player-continuous.dmg
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = osx