# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/son_link/proyectos/mpp/mpp/ui/add_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addDialog(object):
    def setupUi(self, addDialog):
        addDialog.setObjectName("addDialog")
        addDialog.resize(640, 480)
        addDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.gridLayout = QtWidgets.QGridLayout(addDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(addDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.addUrlInput = QtWidgets.QLineEdit(self.tab)
        self.addUrlInput.setObjectName("addUrlInput")
        self.gridLayout_2.addWidget(self.addUrlInput, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.addUrlBtn = QtWidgets.QPushButton(self.tab)
        self.addUrlBtn.setText("")
        icon = QtGui.QIcon.fromTheme("list-add")
        self.addUrlBtn.setIcon(icon)
        self.addUrlBtn.setObjectName("addUrlBtn")
        self.gridLayout_2.addWidget(self.addUrlBtn, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.addSearchBtn = QtWidgets.QPushButton(self.tab_2)
        self.addSearchBtn.setEnabled(False)
        self.addSearchBtn.setObjectName("addSearchBtn")
        self.gridLayout_3.addWidget(self.addSearchBtn, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchInput = QtWidgets.QLineEdit(self.tab_2)
        self.searchInput.setObjectName("searchInput")
        self.horizontalLayout.addWidget(self.searchInput)
        self.searchBtn = QtWidgets.QPushButton(self.tab_2)
        self.searchBtn.setText("")
        icon = QtGui.QIcon.fromTheme("search")
        self.searchBtn.setIcon(icon)
        self.searchBtn.setObjectName("searchBtn")
        self.horizontalLayout.addWidget(self.searchBtn)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.searchResult = QtWidgets.QListWidget(self.tab_2)
        self.searchResult.setObjectName("searchResult")
        self.gridLayout_3.addWidget(self.searchResult, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(addDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(addDialog)

    def retranslateUi(self, addDialog):
        _translate = QtCore.QCoreApplication.translate
        addDialog.setWindowTitle(_translate("addDialog", "Add podcast"))
        self.label.setText(_translate("addDialog", "Insert the feed or a Ivoox podcast URL:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("addDialog", "URL"))
        self.addSearchBtn.setText(_translate("addDialog", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("addDialog", "Search"))
